DROP TABLE IF EXISTS tickets;
CREATE TABLE tickets(
  id SERIAL PRIMARY KEY,
  user_id INT NOT NULL,
  name VARCHAR(100),
  booking_status VARCHAR(50) DEFAULT 'confirmed',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);